imports:
- { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
- { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
- { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
  config:
    contentsCss:
      - "EXT:rte_ckeditor/Resources/Public/Css/contents.css"
      - "EXT:snowboard/Resources/Public/Css/rte.css"

    stylesSet:
    - { name: "Warnhinweis", element: "p", attributes: { 'class': 'alert alert-danger' } }

    format_tags: "p;h1;h2;h3;pre"

    toolbarGroups:
    - { name: styles, groups: [ format, styles ] }
    - { name: basicstyles, groups: [ basicstyles ] }
    - { name: paragraph, groups: [ list] }
    - "/"
    - { name: links, groups: [ links ] }
    - { name: clipboard, groups: [ cleanup, undo ] }

    importModules:
      - { module: '@ckeditor/ckeditor5-word-count', exports: ['WordCount'] }
