<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'PhpParser\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Resources/Private/PHP/PHP-Parser/lib/PhpParser'),
    'Snowboard\\SnowboardStaff\\' => array($typo3InstallDir . 'typo3conf/ext/snowboard_staff/Classes'),
    'Snowboard\\Snowboard\\' => array($typo3InstallDir . 'typo3conf/ext/snowboard/Classes'),
);
