version: "3"
services:
  typo3:
    image: martinhelmich/typo3:10.3
    ports:
      - "80:80"
    volumes:
      - ./site/fileadmin:/var/www/html/fileadmin
      - ./site/typo3conf:/var/www/html/typo3conf
      - uploads:/var/www/html/uploads
    networks:
      - backend
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      - "MYSQL_USER=${MYSQL_USER:-typo3}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-typo3}"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    networks:
      - backend
volumes:
  database:
  uploads:
networks:
  backend:
