base: /
dependencies:
  - praxiswissen-typo3/snowboard
languages:
  -
    title: Deutsch
    enabled: true
    locale: de_DE.utf8
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: Deutsch
    flag: global
    languageId: 0
rootPageId: 14
websiteTitle: 'Snowboardschule Meyer, Müller & Schmidt'
