navigation:
  primaryStartpoint: 15
  secondaryStartpoint: 16
snowboardSchool:
  name: 'Meyer, Müller & Schmidt'
styles:
  content:
    textmedia:
      maxW: 1000
news:
  storagePid: 18
  detailPid: 40
indexedsearch:
  view:
    templateRootPath: 'EXT:snowboard/Resources/Private/Templates/Extensions/IndexedSearch'
    partialRootPath: 'EXT:snowboard/Resources/Private/Partials/Extensions/IndexedSearch'
    layoutRootPath: 'EXT:snowboard/Resources/Private/Layouts/Extensions/IndexedSearch'
  targetPid: 41
