base: 'https://praxiswissen-typo3.ddev.site/'
dependencies:
  - snowboard/snowboard
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
  -
    title: Englisch
    enabled: true
    languageId: 1
    base: /en/
    locale: en_US.UTF-8
    navigationTitle: Englisch
    flag: us
rootPageId: 1
websiteTitle: ''
