name: praxiswissen-typo3/snowboard
label: 'Snowboard'
dependencies:
  - typo3/fluid-styled-content
  - typo3/fluid-styled-content-css
  - typo3/form
  - typo3/seo-sitemap
  - typo3/indexed-search
  - georgringer/news
  - georgringer/news-twb5
